version: '3.8'

services:
  # SQL Server Database Service
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: kpmg-sqlserver
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_PID: "Developer"
      MSSQL_DATABASE: "KPMG_Data_Challenge"
    ports:
      - "3306:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./Database/DDL.sql:/scripts/DDL.sql
      - ./Database/DML.sql:/scripts/DML.sql
      - ./csv-dump/transformed:/data/transformed
    command: >
      /bin/bash -c '
      /opt/mssql/bin/sqlservr &
      sleep 30s
      /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${MSSQL_SA_PASSWORD} -i /scripts/DDL.sql
      /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${MSSQL_SA_PASSWORD} -i /scripts/DML.sql
      tail -f /dev/null
      '

  # Python Application Service
  python-app:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    container_name: kpmg-python
    depends_on:
      - sqlserver
    volumes:
      - ./scripts:/app/scripts
      - ./csv-dump/transformed:/data/transformed
      - ./powerbi_data:/app/powerbi_data
    environment:
      DB_HOST: sqlserver
      DB_USER: sa
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: KPMG_Data_Challenge
      POWERBI_OUTPUT_DIR: /app/powerbi_data
    command: ["python", "scripts/pipeline/pipeline.py"]

volumes:
  sqlserver_data:
